environment:
  matrix:
  - julia_version: 1.5.3

platform:
  - x64 # 64-bit

branches:
  only:
    - master
    - /release-.*/

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - C:\julia\bin\julia -e "using Pkg; Pkg.instantiate()"
  - C:\julia\bin\julia -e "using Pkg; Pkg.build()"
  - C:\julia\bin\julia -e "using Pkg; Pkg.precompile()"

after_build:
  - 7z a julia-depot.7z C:\Users\appveyor\.julia\

artifacts:
  - path: julia-depot.7z
    name: Julia Depot Folder
